site_name: HFUTAIL
site_url: http://tencent.terrytengli.com/
theme: 
        # name: cluster
        name: bootstrap
        # name: material
        include_homepage_in_sidebar: False
        # logo: imgs/hfut_logo.png
        # favicon: imgs/hfut_logo.png

nav:
- Home: index.md
- Members: members/index.md
- Photos: photos/index.md
- Blogs: blogs/index.md
- Devices: devices/index.md
- Public: 
        - Public: public/index.md
        - Books: public/books.md
        - Datasets: public/datasets.md
        - Softwares: public/softwares.md
        - Courses: public/hfut_courses.md
- Mirrors: 
        - Mirrors: mirrors/index.md
        - Anaconda: mirrors/anaconda.md
        - Apt: mirrors/apt.md
- Miscs: miscs/index.md

